// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Тіньова база потрібна лише команді `prisma migrate dev` — вона перевіряє
    // на ній міграцію перед застосуванням. `prisma dev` піднімає її на сусідньому порті.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
